version: '3.8'
services:
  angular-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: ng serve --host 0.0.0.0
    container_name: angular-container
